### ISSUE TITLE
Spare boards in the Uk

### ISSUE THREAD

**Issue by letshin** [vroland/epdiy-hardware#11]
Hi, does anyone have any spares they would be happy to post in the UK/EU?

**Comment by martinberlin** [comment]
Hello Letshin,
Please use the discussion board here:
https://github.com/vroland/epdiy/discussions

This is the Issue board of hardware and not a proper channel to ask for help or boards.
You can also buy a board from me on Tindie next week when I add stock (but only v7 boards)
