### ISSUE TITLE
Alternative to esp32-wroom

### ISSUE THREAD

**Issue by letshin** [vroland/epdiy-hardware#12]
HI, is there an alternative to the esp32-wroom please as JLCPCB says this is only doable on a standard order which adds to the cost of small batches. Is it possible to replace it with a esp-12f for example?

**Comment by martinberlin** [comment]
That’s not a good idea you need to use the chip specified in the BOM.
Do not ask for that part assembled and just solder it yourself. It’s not such a hard work and we’ve all did it at some point even with basic soldiering tools.
Good luck!
