### ISSUE TITLE
SMT component placed incorrectly（by using JLC）

### ISSUE THREAD

**Issue by lmx0125** [vroland/epdiy-hardware#15]
When placing SMT, the component is placed incorrectly.

**Comment by martinberlin** [comment]
Moved to epdiy-hardware since the other main repository is only for the firmware.
@lmx0125 please describe in detail what went wrong I didn’t had this problem when producing the PCB using the provided files

**Comment by martinberlin** [comment]
Closing this since there was no feedback in more than 3 months
