### ISSUE TITLE
R24 confusion

### ISSUE THREAD

**Issue by jonasschnelli** [vroland/epdiy-hardware#18]
In the V7 BOM, R24 has the comment `47.5kΩ ` but `C25819` is `47kΩ`.

```
...
"47.5k","R24","Resistor_SMD:R_0603_1608Metric","C25819"
...
```

https://www.lcsc.com/product-detail/Chip-Resistor-Surface-Mount_UNI-ROYAL-Uniroyal-Elec-0603WAF4702T5E_C25819.html

**Comment by martinberlin** [comment]
Is 47K but is really irrelevant and won’t make any difference if it was 47.5k
I think we can close this unless you find something deeper and that is worth a correction.

**Comment by jonasschnelli** [comment]
I just opened it because the confusion created a feedback question from the PCB manufacturer (delay). Maybe fixing the comment (changing "47.5k" to "47k") would prevent the next person to stumble over this.

I guess changing the .xml file is not the right way? I would expect it is derived from KiCad file?
https://github.com/vroland/epdiy-hardware/blob/504094f94ef042a6004c3bcda421f0379eb24f40/epdiy-v7/epdiy-v7.xml#L1347

Of course I'm also okay with closing it.

**Comment by martinberlin** [comment]
It’s an edge case and it’s the first time I hear that a PCB manufacturer ask for this when they have the exact ID number of the part. But if you feel like fixing it please open a PR. You should edit this with KiCad I’m not entirely sure if it’s that exact part and usually this XMLs are generated automatically by IDE I won’t edit that by hand
