### ISSUE TITLE
About V7 new board

### ISSUE THREAD

**Issue by dengfengdz** [vroland/epdiy-hardware#4]
Hi ,I make some new V7 board，But there are some problems I can't understand，I use the board to display ES108FC1,When I don't plug in the screen，Serial port logs are normal，The voltage at the test point is also normal，When the screen is connected, the voltage will be lowered from +-22v to around +-15.8v.I checked the specs on the chip,The  TPS65185 Maximum support 120mA. Bom message is use the TPS65185 ,But Schematic diagram use TPS651851,The  TPS65185 Maximum support 200mA. So I wonder if this is the reason for my problems.

**Comment by martinberlin** [comment]
Hi @dengfengdz I'm transferring this issue to https://github.com/vroland/epdiy-hardware
Since the Hardware is now over there it can get the right attention in that repository and we keep this one from now on for the component part.

**Comment by dengfengdz** [comment]
I'd like to try but I only have 10.8 "and 13.3" ink screens，I made five V7 boards，only one piece can be displayed properly.This makes me very confused.If it is because the TPS65185 drive capacity is not enough,there's also a drive board that works.

**Comment by dengfengdz** [comment]
I'd like to try but I only have 10.8 "and 13.3" ink screens，I made five V7 boards，only one piece can be displayed properly.This makes me very confused.If it is because the TPS65185 drive capacity is not enough,there's also a drive board that works.
Today, I will buy TPS651851 to try whether it is caused by the problem I said.And I can't find anything else wrong with it.When I'm not connected to the screen,I measured the output voltage on this chip and it's all normal

**Comment by dengfengdz** [comment]
Hi@martinberlin  I have tried to replace TPS651851,The phenomenon is the same as before.I don't have any other ideas right now,
The program will stay stuck in an endless loop,And just like before, when I put my finger on the red area, the program worked
![1](https://github.com/vroland/epdiy-hardware/assets/148832881/255cfcc8-4284-4a2e-bfc7-2f29a6bd6261)
Does this mean that there is something wrong with TPS65185？

**Comment by martinberlin** [comment]
@vroland do you have any idea why it can be that TPS65185 does not trigger the PWRGOOD line?  But it seems to work if he places his finger at the left side marked with the red area.
I never experienced something like this so far.

**Comment by vroland** [comment]
Hm, did you use any alternative parts @dengfengdz for coils, etc? It seems to me like either the TPS is not soldered properly or something else is preventing the boost circuitry from starting up properly. Do you have access to an oscilloscope to measure the voltages in the area you're touching?
