### ISSUE TITLE
ED133UT2 to ED060SC4 adapter described as 33pin while display datasheet for both displays says they are 39pin

### ISSUE THREAD

**Issue by hramrach** [vroland/epdiy-hardware#8]

**Comment by martinberlin** [comment]
I don’t really get this one.

> ED133UT2 to ED060SC4 adapter

Where is that adapter? Can you please be more specific and post a link to it.

The only one I see in new hardware repo is: _**Adapter from 33 pin 9.7" to ED133UT2**_

**Comment by hramrach** [comment]
https://github.com/vroland/epdiy-hardware/tree/main/adapters/33_pin_to_ED133UT2 

https://github.com/vroland/epdiy-hardware/blob/main/adapters/33_pin_to_ED133UT2/README.md
>Adapter from 33 pin 9.7" to ED133UT2
>Warning: The ED133UT2 uses the same physical connector as the ED060SC4, but has a different pin configuration. You can destroy your display if you connect it to the wrong connector!

These are 39pin displays according to specification, not 33pin.

**Comment by martinberlin** [comment]
> These are 39pin displays according to specification, not 33pin.

sure but is clear that is an adapter hence it says:
33 pin to other display

That means that you need to connect it to 33 pins and then it gets out with 39 pin. Again I don’t see the issue.
It should be just properly labeled: Input 33, output 39

**Comment by hramrach** [comment]
Oh, so you are supposed to use a 39pin connector on the board (if you have one, which is not longer the case with v7) for ED060SC4 and the 33pin to 39pin adapter for ED133UT2.

That's completely confusing.

Maybe switching the display type 'specification' to the pin count was a really bad idea.

**Comment by martinberlin** [comment]
No you use a 33 pin from board to adapter and then directly connect the display.
Again there is no 39 pin connector in v7.

Michal if you dislike the board please be my guest and design your own. You already forked this repository so just update it as it pleases you before sending it to fabrication. That’s the greatest thing of open source.
You don’t need to complain about every little thing you dislike. Just change it

**Comment by hramrach** [comment]
Yes, 'just fork'.

The problem is that when the description is bad you have to go through several stages of confusion before doing any actual work on the project. That's a bug that is worth fixing upstream.

**Comment by martinberlin** [comment]
If you tell me your email I will add you to the epdiy channel in Slack. Then in case of any doubt you can talk there with people that already went through testing this or that display and might help you to get started right

**Comment by martinberlin** [comment]
You can also use this new channel to discuss about adapters and get help
https://github.com/vroland/epdiy/discussions
